import type { Metadata } from "next";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer";
import { cookies } from "next/headers";
import { verifyTokenForPage } from "@/utils/verifyToken";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies().get("jwtToken")?.value || "";
  const payload = verifyTokenForPage(cookie);
  return (
    <html lang="en">
      <body>
        <Header payload={payload} />
        <Toaster position="top-right" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
